---
- name: download and extract wordpress
  unarchive:
    src: http://wordpress.org/wordpress-{{ wp_version }}.tar.gz
    dest: /opt
    remote_src: yes

- name: check for /opt/wordpress-{{ wp_version }} existance
  stat:
    path: /opt/wordpress-{{ wp_version }}
  register: wp_dir

- name: copy extracted files to /opt/wordpress-{{ wp_version }}
  copy:
    src: /opt/wordpress/
    dest: /opt/wordpress-{{ wp_version }}
    remote_src: yes
    owner: apache
    group: apache
  when: not wp_dir.stat.exists
  notify: cleanup /opt/wordpress

- name: link /var/www/html to /opt/wordpress-{{ wp_version }}
  file:
    src: /opt/wordpress-{{ wp_version }}
    path: /var/www/html
    state: link
    force: yes

- name: fetch random salts for wordpress config
  uri:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    return_content: yes
  register: wp_salt

- name: create wordpress database
  mysql_db: name={{ wp_db_name }} state=present

- name: create wordpress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present

- name: copy wordpress config file
  template: src=wp-config.php.j2 dest=/var/www/html/wp-config.php owner=apache group=apache
