---  
- name: install apache, php, and php-mysql  
  yum: name={{ item }} state=present 
  loop: 
   - httpd 
   - php 
   - php-mysql 
- name: start and enable httpd 
  service: name=httpd state=started enabled=yes 
